#!/bin/bash

set -e

if [ -f ".deploywebinst.conf" ]; then
	. .deploywebinst.conf
fi

if [ -n "$DEPLOY_DEBUG" ]; then
	set -x
fi

#if [ -z "$DEPLOY_SSH_SU" ]; then
#	DEPLOY_SSH_SU="_www"
#fi

DEPLOY_ID="$(uname -n).$(date +%s).$$"
DEPLOY_SSH_UPLOAD_DIR="/tmp/deploy.${DEPLOY_ID}"

function usage {
    echo "Usage:"
    echo ""
    echo "	$0 <branch-or-commit> </path/to/dynacase-control> <context-name> <module-name> [install|upgrade]"
    echo ""
    echo "Default is 'upgrade'."
    echo ""
    echo "Environment variables:"
    echo ""
    echo "  DEPLOY_SSH=<login@remote.example.net>"
    echo "  DEPLOY_SSH_SU=<setuid_login_on_remote_host>"
    echo ""
}

if [ $# -lt 4 ]; then
    usage
    exit 1
fi

# Parse [--<optName>[ <optValue]]
OPT_UNPACK_ONLY="false"
while [ "$#" -ne 0 ]; do
	case "$1" in
		--unpack-only)
			OPT_UNPACK_ONLY="true"
			shift
			break 2
			;;
		--)
			shit
			break 2
			;;
		*)
			break 2
			;;
	esac
done

COMMIT="$1"
shift
WIFF_PATH="$1/wiff"
shift
CONTEXT_NAME="$1"
shift
MODULE_NAME="$1"
shift
INSTALL_MODE="$1"
shift
if [ -z "$INSTALL_MODE" ]; then
    INSTALL_MODE="upgrade"
fi

ADD_OPTS=""
while [ $# -gt 0 ]; do
	case "$1" in
		--nothing|--quick|--fast|--hurryup)
			ADD_OPTS="$ADD_OPTS --nothing"
			shift
			;;
		--unattended)
			ADD_OPTS="$ADD_OPTS --unattended"
			shift
			;;
		*)
			echo "Unknown argument '$1'."
			exit 1
	esac
done

REPO_ROOT=$(git rev-parse --show-toplevel)

VERSION=$(git show "$COMMIT:VERSION" | head -1)
RELEASE=$(git show "$COMMIT:RELEASE" | head -1)
if [ -f "RELEASE.local" ]; then
    RELEASE=$(head -1 RELEASE.local)
fi

git mkwebinst "${MODULE_NAME}-${VERSION}-${RELEASE}" "$COMMIT"

if [ -n "$DEPLOY_SSH" ]; then
	CURRENT_UID=$(ssh "$DEPLOY_SSH" id -u)
	CURRENT_USERNAME=$(ssh "$DEPLOY_SSH" id -n -u)
else
	CURRENT_UID=$(id -u)
	CURRENT_USERNAME=$(id -n -u)
fi

if [ -z "$DEPLOY_SSH_SU" ]; then
	SETUID_CMD="bash -c"
else
	SETUID_CMD="sudo su -m $DEPLOY_SSH_SU -c"
	if [ "$CURRENT_UID" = "$DEPLOY_SSH_SU" -o "$CURRENT_USERNAME" = "$DEPLOY_SSH_SU" ]; then
		SETUID_CMD="bash -c"
	fi
fi

MODULE_DIR=$(pwd)

if [ -n "$DEPLOY_SSH" ]; then
	ssh "$DEPLOY_SSH" mkdir -m 0700 "${DEPLOY_SSH_UPLOAD_DIR}"
	if [ -n "$DEPLOY_SSH_SU" ]; then
		ssh "$DEPLOY_SSH" chown "${DEPLOY_SSH_SU}:" "${DEPLOY_SSH_UPLOAD_DIR}"
	fi
	scp "$(pwd)/${MODULE_NAME}-${VERSION}-${RELEASE}.webinst" "${DEPLOY_SSH}:${DEPLOY_SSH_UPLOAD_DIR}"
	if [ -f "$(pwd)/${MODULE_NAME}-test-${VERSION}-${RELEASE}.webinst" ]; then
		scp "$(pwd)/${MODULE_NAME}-test-${VERSION}-${RELEASE}.webinst" "${DEPLOY_SSH}:${DEPLOY_SSH_UPLOAD_DIR}"
	fi
	MODULE_DIR="${DEPLOY_SSH_UPLOAD_DIR}"
fi

function _run {
	if [ -n "$DEPLOY_SSH" ]; then
		CMD="'$*'"
		ssh "$DEPLOY_SSH" ${SETUID_CMD} "$CMD"
	else
		CMD="$*"
		${SETUID_CMD} "$CMD"
	fi
}

_run "${WIFF_PATH} context \"${CONTEXT_NAME}\" module "$INSTALL_MODE" --force ${ADD_OPTS} \"${MODULE_DIR}/${MODULE_NAME}-${VERSION}-${RELEASE}.webinst\""
if [ -f "$(pwd)/${MODULE_NAME}-test-${VERSION}-${RELEASE}.webinst" ]; then
	_run "${WIFF_PATH} context \"${CONTEXT_NAME}\" module "$INSTALL_MODE" --force ${ADD_OPTS} \"${MODULE_DIR}/${MODULE_NAME}-test-${VERSION}-${RELEASE}.webinst\""
fi
_run "${WIFF_PATH} context \"${CONTEXT_NAME}\" exec /usr/bin/env sed -i\"\" -e \"s/ExpiresActive On/ExpiresActive Off/g\" .htaccess"

if [ -n "$DEPLOY_SSH" ]; then
	ssh "$DEPLOY_SSH" rm -Rf "${DEPLOY_SSH_UPLOAD_DIR}"
fi

# espeak "Module successfully deployed." > /dev/null 2>&1

echo "[DONE]"
